### ISSUE TITLE
Livrable

### ISSUE THREAD

**Issue by CrumbleZ** [thomasroulin/ROTFW#1]
Faudrait qu'on commence à mettre tout dans la même scène

Parce qu'en soit, il nous manque plus qu'une pizza et placer des bouées... Et on a gagné non ?

**Comment by roflolilolmao** [comment]
Vaguement.

Il faut encore une gestion de ressources, de vagues, peut-être plusieurs types d'ennemis.

**Comment by CrumbleZ** [comment]
Vu le temps qu'il nous reste, je suis pas certain que ce soit une priorité mais si on s'y fout à fond Samedi, ca peut le faire je pense.

Si on fait des priorités dans l'ordre

1. Pizza
2. Bouées
3. Gestion de l'or gagné
4. Acheter des tours pour les placer
5. Vagues d'ennemis
6. Gestion de l'expérience gagnée
7. Variation des ennemis

Ca parait bien ?

**Comment by roflolilolmao** [comment]
:+1:

**Comment by CrumbleZ** [comment]
Vendu... je fais une issue par tâche alors et je retourne à mon QdL
