### ISSUE TITLE
fix pathfinding

### ISSUE THREAD

**Issue by roflolilolmao** [thomasroulin/ROTFW#9]
it's broken yo

**Comment by roflolilolmao** [comment]
might need some more testing but flemme intense right now

**Comment by roflolilolmao** [comment]
clearly still buggy

**Comment by thomasroulin** [comment]
Should I open a new Issue for that ?:
- [ ] Prevent user from creating a blocking wall that takes the whole screen.

**Comment by roflolilolmao** [comment]
no need yet, i'll fix the pathfinding first

**Comment by roflolilolmao** [comment]
ok so if no path is found, the whales will just ignore the turrets

they sometimes stop for no reason so i'll just pretend i didnd't notice and close this issue

**Comment by CrumbleZ** [comment]
About the pizza, it looks like they stop once they reach it on the x-axis.
About the turrets, they tend to stop when near the shooting range of a turret, or near the turret itself...

I've no idea why but this might help youg get a clue a about it.

**Comment by roflolilolmao** [comment]
still buggy ? It's weird i tested my last version and it seemed fine, i guess i'll continue working on that tomorrow
